### ISSUE TITLE
Restore domains to seq ontology and remove from version in VitroLib instead

### ISSUE THREAD

**Issue by rjyounes** [LD4P/arm#101]
@sfolsom I think it's best not to alter the ontology fragments stored in this repository, but rather to modify those stored in VitroLib. What do you think?

**Comment by sfolsom** [comment]
Sure. I was going for a quick fix. Not sure how we implement this... We'll have to figure out a way to make sure these types of changes take place when pulled into VitroLib. In general though, I'd hope people would go to the source ontology to get the whole picture.

**Comment by rjyounes** [comment]
Yes, I realize there is this complication. In general, updating the ontologies in VitroLib (as in VIVO and any other ontology-driven application) cannot be done without preparation, so it is expected that before pulling from the ARM repository the VitroLib developer will need to run diffs and consider how this will affect functionality of the application. 

While I agree that people should go to the source as authoritative, I still think it's important to accurately reflect term definitions in our fragments. Since you agree to the change, I'll restore the domains here and remove them from the VitroLib ontology file. I don't believe VitroLib will be pulling ontology changes from ARM during the remainder of this project anyway.

**Comment by sfolsom** [comment]
FYI, Turns out there are (at least) three seq target files. One or more of them still have the domains defined.

**Comment by rjyounes** [comment]
Will be handled by #108

**Comment by rjyounes** [comment]
@sfolsom I created #248 in VitroLib repo to remove the domains in the VitroLib ontology file. But do we currently want these predicates to show up on any entity types? If so, then if we remove them from the onto file we'll need to create faux properties for them.
