### ISSUE TITLE
Clean up application_profiles/source/ontologies

### ISSUE THREAD

**Issue by rjyounes** [LD4P/arm#108]
When I (Rebecca) reorganized the repository a few months ago, I dumped all the source ontology files into a single directory: https://github.com/LD4P/arm/tree/develop/application_profiles/sources/ontologies. So there are now multiple versions of various source ontologies (e.g., 4 versions of dcterms). They are also not up-to-date - e.g., we don’t use cito at all anymore. Someone needs to undertake the possibly tedious task of sorting through these files, creating one file for each ontology we’re actually using in our application profiles, and including only the terms that we have specified. The latter is complicated by the fact that the SHACL profiles may not use all the terms actually identified in the models in the recommendation docs - but then, these are not up-to-date either. It requires some institutional memory.

**Comment by sfolsom** [comment]
I'm sure there are errors, but this section of the repository is much cleaner now. There are still questions about certain classes that were used either for look-ups (e.g. lingvo:Lingvo and geonames:Feature) vs. what we stated in the pattern docs and our decision to go with BF terms where possible. Same goes for some classes like schema:Event vs. bf:Event, where we're waiting on recommended changes from BF. @jak473 @melanieWacker, please feel free to direct in a different direction, but for now I'll close this issue.
