### ISSUE TITLE
Document maintenance of validation and form SHACL

### ISSUE THREAD

**Issue by rjyounes** [LD4P/arm#109]
Rebecca and Steven to take leads in their respective areas
Forms: E.g: community involvement in what entities should look-like; e.g.: in VitroLib can say what something looks like in brief view… similar to headings in AAPs. community to consider which parts of a graph are relevant to present to a user in brief/list view
Validation: Definitions beyond what is provided in ontologies… what the RDF should look like. These are represented in the Validation shapes in the GH Application Profile directories. Formal expression of what Validation would entail / formal expression of our models

**Comment by sfolsom** [comment]
What form should this take? A single README under https://github.com/LD4P/arm/tree/develop/application_profiles? Separate docs? 

I have some issues related to SHACL/Application Profile maintenance/future considerations written down in a "What VitroLib Has Taught Us" outline I had started when we were prompted to begin considering documentation for Vitrolib (before this new action item): https://docs.google.com/document/d/1rJnURj2jtiVvMtPs1PBtmWXHK5sHH5RMv16vpoBhxEk/edit?usp=sharing. Perhaps we tease apart the application profile documentation from the Vitrolib documentation, and link where appropriate?

Also, I'm not sure if we should separate list view documentation or not... The work is spurred by Vitrolib needs. The approach we used (expected by Vitro) was SPARQL. That said, it's really important work to consider to replace the authorized access point approach to Authority Heading creation in traditional cataloging; catalogers should own this on some level. Also, there's probably a way in SHACL to define these views, some are using SHACL for UI configurations like this, but we don't necessarily have to go in this direction.

**Comment by rjyounes** [comment]
I thought we could each write our sections and then combine them into a single doc. What is the scope of the doc? Will it include Melanie's SHACL or not? That would suggest at what level the document should reside. 
 
As I see it the doc should not contain anything beyond the SHACL that relates only to VitroLib, such as the list view configs. Your writeup of the form/UI shapes will need to reference VitroLib since it is specifically tailored towards it.

**Comment by sfolsom** [comment]
The scope needs to be what someone/s would need to know to take on the maintenance of the SHACL beyond the grant (assuming it gets picked up by an organization/s). It seems we could generalize our findings across ARTFRAME and RareMat and still have a document that is useful, especially since it hasn't been determined whether the two organizations will collaborate on this in the future. @melanieWacker, thoughts?

**Comment by melanieWacker** [comment]
Yes. A generalized document would be more useful -- even in a broader context, e.g. somebody may just consider using SHACL for this purpose and wants to get an idea of the long-term issues involved.

**Comment by rjyounes** [comment]
Status: writing largely done and ready to be converted to markdown and added to github; further edits may occur subsequently.
