### ISSUE TITLE
Submit ARM BIBFRAME recommendations as issues in LC BF repository

### ISSUE THREAD

**Issue by rjyounes** [LD4P/arm#110]
There will be a consistency issue across documents
Process: list outside of GitHub first to then add Issues later, once we ensure that no conflict exist
Figure out a format so that LC is aware that these derive from ARM and not from an individual

**Comment by sfolsom** [comment]
Update: The document listing potential issues has been created. "Clear cut" recommendations have been added, and we are working through the more murky issues.

**Comment by zimeon** [comment]
See: https://github.com/lcnetdev/bibframe-ontology/issues/created_by/sfolsom and https://github.com/lcnetdev/bibframe-ontology/issues/created_by/melanieWacker

**Comment by melanieWacker** [comment]
Update: Submitted all "art only recommendation" issues

**Comment by sfolsom** [comment]
All issues agreed to by ARM have been submitted to LoC. cc: @jak473 (note the links Simeon added in a comment above if you want to see them all in one place... well, two places)
