### ISSUE TITLE
Vocabulary dataset definitions don't give namespace URI

### ISSUE THREAD

**Issue by zimeon** [LD4P/arm#115]
I notice that the vocabulary files (e.g. https://github.com/LD4P/arm/blob/develop/core/vocabularies/arrangement/0.1/arrangement.rdf) don't actually list in the RDF dataset description the namespace URI that corresponds with the `vann:preferredNamespacePrefix`.

```
<void:Dataset rdf:about="https://w3id.org/arm/core/vocabularies/arrangement/">
        <owl:versionInfo rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Version 0.1.0</owl:versionInfo>
        <dcterms:issued>2018-04-27T00:00:00-04:00</dcterms:issued>
        <dcterms:modified>2018-04-27T00:00:00-04:00</dcterms:modified>
        <rdfs:label xml:lang="en">Art and Rare Materials Arrangement Vocabulary</rdfs:label>
        <dcterms:title xml:lang="en">Art and Rare Materials Arrangement Vocabulary</dcterms:title>
        <skos:definition xml:lang="en">The Art and RareMat Arrangement Vocabulary is a controlled vocabulary to express the physical arrangment or configuration of objects described in rare materials metadata. Arrangements may apply to individual objects or collections of objects.</skos:definition>
        <skos:editorialNote xml:lang="en">The elements of this vocabulary are typed https://w3id.org/arm/core/ontology/0.1/Arrangement rather than http://id.loc.gov/ontologies/bibframe/Arrangement because at the time of publication BIBFRAME Arrangement is used only with collections of objects and not individual objects. Should this definition change in future versions of BIBFRAME, the entities defined here will be retyped.</skos:editorialNote>
        <vann:preferredNamespacePrefix>arrangement</vann:preferredNamespacePrefix>
        <void:vocabulary rdf:resource="https://w3id.org/arm/core/ontology/0.1/"/>
    </void:Dataset> 
```

Should this be added with [`vann:preferredNamespaceURI`](http://vocab.org/vann/#preferredNamespaceUri) or some other property?

**Comment by rjyounes** [comment]
Can you clarify this? The definition of vann:preferredNamespacePrefix is:

The preferred namespace prefix to use when using terms from this vocabulary in an XML document

Isn't it assumed that the prefix represents the vocabulary namespace, which is given in the void:Dataset declaration? Or do you mean that the versioned URI should be specified using vann:PreferredNamespaceURI?

**Comment by zimeon** [comment]
But the `void:Dataset` declaration gives an unversioned URI which isn't the namespace of anything. There should be somewhere which gives the actual namespace of the terms defined

**Comment by rjyounes** [comment]
How does this differ from the ontology setup? Is it because the ontologies specify both an ontologyIRI and a versionIRI?

**Comment by zimeon** [comment]
Nowhere in the current `void:Dataset` declaration is the actual namespace URI specified, that seems an omission (especially because I want to pull it out during the doc generation #80 :-) ) Could it even be that `void:Dataset` should give the actual namespace?

**Comment by rjyounes** [comment]
That's what I'm wondering. I will think for a bit and then either use the versioned URI in the void:Dataset declaration, or add the vann:PreferredNamespaceURI assertion.

**Comment by rjyounes** [comment]
Changed Dataset declaration to use actual (versioned) namespace: e.g., https://w3id.org/arm/core/vocabularies/arrangement/0.1/
