### ISSUE TITLE
Reorganize LODE doc directory structure 

### ISSUE THREAD

**Issue by rjyounes** [LD4P/arm#120]
Move award/ontology/0.1/doc/lode/award.html to award/ontology/0.1/, and similarly for other HTML LODE files.

Requires:
- moving files and eliminating directories
- modifying the doc generator script
- modifying redirects
- modifying index

**Comment by zimeon** [comment]
Have put in PR to change the redirects to remove `doc/lode` portion of path.

https://github.com/perma-id/w3id.org/pull/1034

When this goes live I'll update the github pages site

**Comment by rjyounes** [comment]
HTML pages have been moved and doc directories deleted.

**Comment by zimeon** [comment]
Yes, I merged #124 but still waiting for w3id folks to update the links...

**Comment by zimeon** [comment]
w3id changes were merged a while ago so https://w3id.org/arm/core/ontology/0.1/core.html etc. now work
