### ISSUE TITLE
Fix incorrect redirect

### ISSUE THREAD

**Issue by rjyounes** [LD4P/arm#125]
https://w3id.org/arm/core/ontology/0.1/activity.rdf redirects to https://ld4p.github.io/arm/core/ontology/0.1/core.html#activity.rdf

Should redirect to 
https://ld4p.github.io/arm/core/ontology/0.1/activity.rdf

**Comment by rjyounes** [comment]
My mistake, I see that's what was requested. However, I think the original request was in error: it should actually be:

https://w3id.org/arm/core/activity/0.1/activity.rdf => https://ld4p.github.io/arm/core/activity/0.1/activity.rdf

and

https://w3id.org/arm/core/activity/0.1/activity.html => https://ld4p.github.io/arm/core/activity/0.1/activity.html

We DO want to have activity under core, to show that it is in fact part of the core, but we're using "core/ontology" to reference core.rdf, which "core/activity" to reference activity.rdf would parallel.

https://ld4p.github.io/arm/core/ontology/0.1/activity.(rdf|html) doesn't really make sense.

Sorry for all the confusion.

**Comment by zimeon** [comment]
If you want to change the pattern as described above (https://github.com/LD4P/arm/issues/125#issuecomment-399553456) then you'd need to move activity the files in this repository from `core/ontology/0.1/` to `core/activity/0.1/`. That choice might address the issue of making the namespace URI match the https://ld4p.github.io/ URI, but does instead break the rule of everything that is an ontology being in an `/ontology/` directory.

I'm not convinced that grouping these two ontologies under `core` has any benefit, it seems you might be better letting that go and just calling one thing `core` and the other thing `activity` (even if it is an important part of the ontology cluster). Then you could used the regular pattern `activity/ontology/0.1/` and nobody will be confused whether core means just `core.rdf` or both `core.rdf` and `activity.rdf`.

**Comment by rjyounes** [comment]
OK, let's do it that way activity/ontology/0.1. I'll move the files and change the namespaces and alert you when it's done.

**Comment by zimeon** [comment]
OK, it is good to make the files in new locations live (and this current redirects broken) as the w3id folks want the new destinations to work in order to merge the redirect changes

**Comment by rjyounes** [comment]
I've changed the namespace and moved the files in PR #127. You will need to regenerate the LODE docs in addition to informing w3id of the new redirects. 

Just to make sure we're on the same page, the new namespaces are:
Unversioned: https://w3id.org/arm/activity/ontology/
Versioned: https://w3id.org/arm/activity/ontology/0.1/

Thanks.

**Comment by zimeon** [comment]
Have updated LODE and generation script in d9e192ddfcfd6396ecbf56fae389740b6fc8b562 , now live at https://ld4p.github.io/arm/activity/ontology/0.1/activity.html and will put in request to update redirect...

**Comment by zimeon** [comment]
Redirect changes now live and working, e.g.:
  * https://w3id.org/arm/activity/ontology/
  * https://w3id.org/arm/activity/ontology/0.1/
  * https://w3id.org/arm/activity/ontology/0.1/Scribe

**Comment by zimeon** [comment]
Since everything was moved around per discussion on this issue, it is now `done, another way`, closing.
