### ISSUE TITLE
Display skos:definition in vocabulary LODE documentation

### ISSUE THREAD

**Issue by rjyounes** [LD4P/arm#126]
This is missing from the LODE doc. Perhaps the skos:definition on the void:Dataset is not getting converted to an rdfs:comment when generating the documentation.

**Comment by zimeon** [comment]
Problem is that LODE entirely ignores information about `void:Datasets`, fixed in 55c77e7 with hacks to make LODE think that the vocabs have an `owl:Ontology` description
