### ISSUE TITLE
Comments on ARTFrame title types

### ISSUE THREAD

**Issue by rjyounes** [LD4P/arm#24]
The recommendation does not provide explicit definitions of the proposed new title types, so I can only guess what they mean, based in part on previous discussion.

- CreatorsTitle, as I've suggested elsewhere, looks like a title source rather than a title type. That is, the source points to the same agent that is linked to the CreationActivity on the Work.
- RepositoryTitle: is this the title assigned by the repository? If so, also a source: the holding institution.
- DescriptiveTitle: not sure what this is. Could be a good candidate for a title type.
- TranslatedTitle: how does this differ from ParallelTitle?
- OriginalTitle and FormerTitle: could these be handled by date designations on titles? This would simplify, for example, deprecating one title to a former title and assigning a new title (this by itself suggests that it's not a typing issue). Rather than changing the type of the first title, one would add an end date to it. If specific dates are not known, then seq:precedes and seq:follows could be used. Admittedly, this seems like a more complicated approach, but it makes more sense to me than calling these different types of titles.
- ExhibitionTitle: this looks like a relationship between the title and the item in the context of an exhibition. Typing it this way won't tell us in which exhibition it had this title; to do that, we would need a relationship anyway; so then the typing is redundant. Could the ExhibitionEvent or the Catalog be the source of the title instead of assigning a title type? Or how about a predicate hasContext, which could perhaps be widely useful. That is, :item bf:Title :title . :title ex:hasContext :exhibitionEvent. I'm not sure; we might have other ways of expressing this that don't involve a new predicate. Maybe a predicate hasContext suggests that we actually need a context node. I made [some remarks about context nodes in the recommendation doc](https://docs.google.com/document/d/1QCqa31m68Tj69PDyWzJfAFFNcI2DDiMSRsIQ49VGGTA/edit?disco=AAAABjMBD_I), but I'm not sure that it can handle the title case. That is, if there's an Exhibition context node, is it correct to assign the exhibition title to it? I'm not sure. 

@melanieWacker Could we talk through these a bit more so I understand the issues?

**Comment by rjyounes** [comment]
@melanieWacker Of those remaining (TranslatedTitle, OriginalTitle, FormerTitle), none of them are defined in core.rdf. Was this an oversight, or did you decide to drop these as well? Let me know and we can close out the issue.

**Comment by rjyounes** [comment]
OK, I will add them to core.rdf.

**Comment by rjyounes** [comment]
@melanieWacker I see why it happened - they are not actually in the recommendation. Can you either add them to core.rdf or provide definitions here so I can add them? Thanks!

**Comment by melanieWacker** [comment]
@rjyounes My apologies. Rereading our documentation I am realizing that the only title type we still need is translated title. That's why that is the only one with a definition in the recommendation: "Value translated from another language, not transcribed from the resource itself."

**Comment by rjyounes** [comment]
@melanieWacker In the document that is an origin rather than a title type, and we do have it in the origins vocabulary.

**Comment by melanieWacker** [comment]
Absolutely. I think it's too hot for me today to think. That makes it easy, though. We can close this issue,
