### ISSUE TITLE
Create SHACL for Bindings and Enclosures

### ISSUE THREAD

**Issue by rjyounes** [LD4P/arm#45]

**Comment by sfolsom** [comment]
I'm attempting to review this, and I don't believe you can create general form shapes e.g. the one used for hasMaterial.

**Comment by sfolsom** [comment]
Is there a reason why rdfs:labels are used for NodeShapes and sh:name for PropertyShapes?

**Comment by rjyounes** [comment]
Re general form shapes: let's discuss this. I don't know what you mean by "can't create."

Re labels and names: I was following your practice here. The SHACL doc mentions sh:name only in relation to PropertyShapes, though I don't know if that means they can't be used with NodeShapes.

**Comment by sfolsom** [comment]
The pulling in of validation shapes seems to be working. (If I understand sh:and and the different files.) We'll need to figure out what we mean by validation in the project and community, e.g. is what we've capture in our shapes the highest level ideal for the ontologies we've developed? Will there be closed shapes? Or will we allow open shapes? Will there be different levels of severity?

**Comment by sfolsom** [comment]
Because I had been copying and pasting from TopBraid output, I hadn't realize I had been following that pattern too. I had assumed sh:name was applicable to a NodeShape or a PropertyShape. It's *interesting * that they make these distinctions about what are essentially just labels.
