### ISSUE TITLE
Create SHACL for Carriers and Bound-with

### ISSUE THREAD

**Issue by sfolsom** [LD4P/arm#51]
https://github.com/LD4P/ArtFrame-RareMat/blob/develop/modeling_recommendations/carriers_and_bound_withs.md

re: Bound-with, hasPart is currently available at the bf:Item level, but unsure if arm:BoundCollection is a bf:Item or requires a separate form.

need to add arm:isOnCarrier to bf:Item form, but need to know what a Carrier form would look like. Can we just treat it as an Item, or do we need a new Carrier class?

**Comment by rjyounes** [comment]
It seems that arm:BoundCollection should be a subclass of bf:Item, but if so, that was overlooked in the definition. Is there a problem that it is not attached to an Instance? I will shoot a Slack to the RareMat group to check.

A carrier is not an item. We are using crm:P2_has_type with AAT terms. Do you think it needs something more?
