### ISSUE TITLE
Streamline fix anchors process

### ISSUE THREAD

**Issue by rjyounes** [LD4P/arm#57]
Take the following arguments rather than hard-coding the values:
- prefix (URI)
- input filename
- output filename

Otherwise the script has to be edited every time it's used, or we have to maintain multiple copies of the file (which is currently the case, just for a quick solution).

**Comment by rjyounes** [comment]
Script could also incorporate all steps documented in doc/lode.md so the steps don't have to be executed separately.

I think it would still be good to be able run the process on a single rdf file rather than all files in batch. Possibly two scripts are needed: one to perform the modifications on a single file, the second to orchestrate the execution on all rdf files in the repository. This would allow either to be run, depending on needs.

**Comment by zimeon** [comment]
See #80 instead. Closing.
