### ISSUE TITLE
Set up redirects from w3ids with conneg

### ISSUE THREAD

**Issue by zimeon** [LD4P/arm#58]
List of redirects to set up (from @rjyounes) follow pattern:

**Unversioned URIs --> versioned URIs**
  * https://w3id.org/arm/award/ontology/ --302--> 
    * https://w3id.org/arm/award/ontology/0.1/
  * https://w3id.org/arm/award/ontology/award.rdf --302--> 
    * https://w3id.org/arm/award/ontology/0.1/award.rdf
  * https://w3id.org/arm/award/ontology/award.html --302-->
    * https://w3id.org/arm/award/ontology/0.1/award.html

**Versioned URIs -> content**
  * https://w3id.org/arm/award/ontology/0.1/award.rdf --302-->
    * https://ld4p.github.io/arm/award/ontology/0.1/award.rdf
  * https://w3id.org/arm/award/ontology/0.1/award.html --302-->
    * https://ld4p.github.io/arm/award/ontology/0.1/doc/lode/award.html
  * https://w3id.org/arm/award/ontology/0.1/ --303-conneg--> 
     * https://ld4p.github.io/arm/award/ontology/0.1/award.rdf &
     * https://ld4p.github.io/arm/award/ontology/0.1/doc/lode/award.html

and also for each of the following (only rdf listed):

  * https://w3id.org/arm/core/ontology/0.1/ => https://ld4p.github.io/arm/core/ontology/0.1/core.rdf 
  * https://w3id.org/arm/core/activity/0.1/ => https://ld4p.github.io/arm/core/ontology/0.1/activity.rdf
  * https://w3id.org/arm/core/vocabularies/arrangement/0.1/ => https://ld4p.github.io/arm/core/vocabularies/arrangement/0.1/arrangement.rdf
  * https://w3id.org/arm/core/vocabularies/handwriting_type/0.1/ => https://ld4p.github.io/arm/core/vocabularies/handwriting_type/0.1/handwriting_type.rdf
  * https://w3id.org/arm/core/vocabularies/origin/0.1/ => https://ld4p.github.io/arm/core/vocabularies/origin/0.1/origin.rdf
  * https://w3id.org/arm/core/vocabularies/status/0.1/ => https://ld4p.github.io/arm/core/vocabularies/status/0.1/status.rdf
  * https://w3id.org/arm/core/vocabularies/typeface/0.1/ => https://ld4p.github.io/arm/core/vocabularies/typeface/0.1/typeface.rdf
  * https://w3id.org/arm/custodial_history/ontology/0.1/ => https://ld4p.github.io/arm/custodial_history/ontology/0.1/custodial_history.rdf
  * https://w3id.org/arm/measurement/ontology/0.1/ => https://ld4p.github.io/arm/measurement/ontology/0.1/measurement.rdf

**Comment by rjyounes** [comment]
@zimeon If it makes sense to set up the redirects for the other html files so they work once the files are in place, you can go ahead. I can provide the mapping or you can follow the pattern above.

**Comment by rjyounes** [comment]
I just saw that the link to JS and CSS files is wrong - will fix.

**Comment by zimeon** [comment]
Re: https://github.com/LD4P/arm/issues/58#issuecomment-385089488 -- I have been updating issue description as I work out the mapping pattern

**Comment by rjyounes** [comment]
Link fixed.

**Comment by zimeon** [comment]
NB. this pattern `https://w3id.org/arm/core/activity/0.1/` => `https://ld4p.github.io/arm/core/ontology/0.1/activity.rdf` is different from all others, seems that it should really have been `https://w3id.org/arm/activity/ontology/0.1/` etc.

**Comment by rjyounes** [comment]
Yes, I realize that. activity.rdf is viewed as part of the core ontology. If we continue to use the activities, they will be merged into core.rdf. Otherwise, it will be removed. So we wanted to store it with the core and use the URI to signal this.

**Comment by zimeon** [comment]
Done. The URLs above and matching patterns for the other ontos/vocabs are live. Generation and test code in https://github.com/zimeon/w3id-test-arm.

If there are problems then best to create new issues.
