### ISSUE TITLE
Namespace for raremat_monograph_form

### ISSUE THREAD

**Issue by rjyounes** [LD4P/arm#62]
@sfolsom If our namespaces are going to reflect the directory structure, shouldn't the raremat_monograph_form namespace be: https://w3id.org/arm/application_profiles/raremat_monograph/shacl/raremat_monograph_form/ ?

Ditto for raremat_monograph_property_groups.

This is how I've namespaced my files, and that's how my prefixes for your files read. We need to get these in sync, obviously.

P.S. Despite my earlier suggestion of the singular "application profile", I've changed the folder name to the plural because it does indeed contain multiple profiles (raremat and art). If it were just multiple files for a single application, it would be more appropriate to use the singular.

**Comment by rjyounes** [comment]
Or maybe you weren't expecting the namespaces to reflect the directory structure. In any case, I'm confused.

**Comment by sfolsom** [comment]
I misinterpreted a comment you made previously about redundancy in the URI. If keeping the directory matching the URI is important... Maybe the URI should be https://w3id.org/arm/application_profiles/raremat_monograph/shacl/form/ .

**Comment by zimeon** [comment]
There is no requirement for directory structure to match the URIs. The directory structure should be whatever is easiest to understand and manage (which maybe happen to match URIs, or may not)

**Comment by rjyounes** [comment]
I realize there's no such requirement, but other things being equal it seems simpler if they do. AFAIK other things _are_ equal.
