### ISSUE TITLE
Download Getty AAT hierarchy for binding components as RDF

### ISSUE THREAD

**Issue by rjyounes** [LD4P/arm#72]
Need descendants of http://vocab.getty.edu/aat/300194225 (binding components) as RDF. So far have not been able to do this using the SPARQL endpoint or other means.

**Comment by sfolsom** [comment]
I've been using the following query then download the RDF: describe * {?x gvp:broaderExtended aat:300194225}

**Comment by rjyounes** [comment]
Thanks.
