### ISSUE TITLE
Replace dcterms:hasPart/isPartOf with bf:hasPart/partOf

### ISSUE THREAD

**Issue by rjyounes** [LD4P/arm#73]
I've just realized that BF DOES define an object property hasPart, inverse partOf. I'd been looking only at the datatype property part. @jak473 @sfolsom @melanieWacker Should we change our application profiles to use the BF predicates?

**Comment by melanieWacker** [comment]
I assumed that's what we would do in the spirit if aligning back to BIBFRAME, so I used bf:hasPart in the Art profile shacl.

**Comment by rjyounes** [comment]
Removing question mark - fix in raremat profiles.

**Comment by sfolsom** [comment]
the forms SHACL uses bf properties

**Comment by rjyounes** [comment]
Done
