### ISSUE TITLE
Modify custodial history form to manage CustodialHistory behind the scenes

### ISSUE THREAD

**Issue by rjyounes** [LD4P/arm#74]
Not sure if we want the form to link the Item to a CustodialHistory, and then add the CustodialEvents, or whether we should just add the CustodialEvents and link to the CustodialHistory behind the scenes. In fact, a CustodialHistory resource could be created for the Item when the Item is created. It depends on what makes sense to the catalogers.

**Comment by sfolsom** [comment]
Cataloger preference is to go directly to Events, bypassing the CustodialHistory

**Comment by rjyounes** [comment]
Need to check with Huda to see if this will not be too complex. I suggest creating a CustodialHistory resource and attaching it to the Item when the Item is created. Then when CustodialEvents are created, they can be attached to the CustodialHistory object without checking first to see if it exists.
