### ISSUE TITLE
Convert additional RBMS XML vocabularies to RDF

### ISSUE THREAD

**Issue by rjyounes** [LD4P/arm#83]
All vocabularies are now in /tools/rbms_vocabs/data. We will want to put these in namespaces like https://w3id.org/arm/core/vocabularies/rbms_genre/0.1/> etc. and the RDF output in /core/vocabularies/rbms_genre/0.1/ etc.

@timathom Would you be willing to run your XSL on the additional vocabularies? I think it just requires a change of the namespace, so someone else could do it too if you don't have the time. (I don't think we should create different XSLs for each namespace, but maybe just add a note about modifying it as needed.) I believe we will not be using any of the other vocabularies for VitroLib -- @jak473 please correct me if I'm wrong -- so this is not top priority, but it would be nice to have it done. 

I'm assigning this to myself just so I remember to keep track of it.

**Comment by timathom** [comment]
Yes, I can work on this. Should I add the "type" suffix to any of the namespaces? Or do we need this suffix at all?

**Comment by rjyounes** [comment]
The "type" suffix was just for the type vocabulary. The namespaces should all have "rbms_" as a prefix, so that it's clear they are RBMS vocabs and not ours.

Thanks a lot!

**Comment by rjyounes** [comment]
@timathom Do you think we should manually add an rdf:Description of the entire vocabulary at the top of each file, to identify the source and date of the export? We could use type void:Dataset, or not.

**Comment by timathom** [comment]
Yes, I was thinking of generating a skos:ConceptScheme resource for each vocab (e.g., http://id.loc.gov/authorities/genreForms.skos.rdf), but could use void:Dataset, depending on preference.

**Comment by rjyounes** [comment]
Forgot about skos:ConceptScheme. That would be preferable.

**Comment by rjyounes** [comment]
@timathom Your question about the "_type" affix got me thinking, and actually looking at the vocabulary I realized it's not "type" in the sense of "kind" but in the sense of "typeface." This is not what I wanted. Is there a way to produce a vocabulary of binding types? It looks like type is mixed into a lot of the different hierarchies.

**Comment by rjyounes** [comment]
@timathom Your question about the "_type" affix got me thinking, and after looking at the original XML file I realized the binding namespace should just be https://w3id.org/arm/core/vocabularies/rbms_binding/0.1# without "_type." Sorry about the confusion.

**Comment by timathom** [comment]
Okay, that makes sense. Also, I had been using `/`instead of `#` on the namespace. I guess `#` is preferred for SKOS?

**Comment by rjyounes** [comment]
I'm not sure if you're asking me or telling me :). If it's preferred, then let's use it. Do you want to change the existing files or should I?

**Comment by rjyounes** [comment]
Can you send me a reference for # being preferred for skos vocabularies?

In general I prefer / because with # the entire document is returned for any requested term. That could be problematic on large vocabularies.

**Comment by timathom** [comment]
Oh, I noticed that you had switched to `#` in your last update, and I remembered seeing that in other SKOS vocabs, so I was going on that :)

**Comment by rjyounes** [comment]
I think it must have been you and I didn't notice it in your files - I've used / in my SHACL file.

In this variable assignment you have neither slash nor hash:

<x:param name="base-uri"
    >https://w3id.org/arm/core/vocabularies/rbms_binding/0.1</x:param>
Is that correct?

**Comment by timathom** [comment]
Yes, I was adding the slash later, but I will update so that everything is consistent.

**Comment by rjyounes** [comment]
OK, I'll leave it to you to make all the namespace updates so that we aren't stepping on one another's toes. Thanks.
