### ISSUE TITLE
Assign sh:order to Item-level property shapes

### ISSUE THREAD

**Issue by rjyounes** [LD4P/arm#85]
raremat_shapes_monograph_exhibition:ItemForm_arm_hasExhibition (not yet active but let's assign an order now anyway)

raremat_monograph_custodial_history:ItemForm_ch_hasCustodialHistory_bf_hasPart

@sfolsom Can you supply me with the correct values, or add them in yourself? Thanks.

**Comment by sfolsom** [comment]
I'll add them. Do you want me to finish the incomplete Exhibition SHACL?

**Comment by rjyounes** [comment]
Thanks. 

I'll finish the exhibition SHACL while I'm waiting to work on custodial history.
